name = "stremio-story-order"
main = "worker.js"
compatibility_date = "2026-09-17"
workers_dev = true
preview_urls = true

[vars]
ENABLE_CUSTOM_UPSTREAM = "false"
ALLOWED_UPSTREAM_HOSTS = ""

[[kv_namespaces]]
binding = "STORY_CACHE"
id = "3e588f25be544699875409d2478050c8"